name: Run Test and Deploy Result page

on: 
  workflow_dispatch:
    inputs:
      testBranch:
        description: "Which branch to checkout and run test"
        required: false
        default: master
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false

      - name: Run Tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: npm run cypress:run

      # - name: Copy test execution videos
      #   run: |
      #     mkdir public
      #     cp -r cypress/videos public/videos

      - name: Merge test results into one
        run: npm run report:merge

      - name: Generate HTML report
        run: npm run report:generate

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public


